### ISSUE TITLE
User Story #1 - Home Page

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#1]
### User Story #1

As a **Customer**, I want to be able to **navigate the site's home page** so that I can **familiarize myself with the type of products and services offered, identify clearance items and special offers.**

#### Acceptance Criteria  
- [x] **AC 1:** The home page displays a straightforward navigation menu with links to product categories, special offers, and the clearance section.  
- [x] **AC 2:** A search bar is available and functional for quick access to the various links and categories of the products.  
- [x] **AC 3:** A carousel container with appealing images of finger foods, summarized descriptions, and persuasive call-to-action phrases encouraging product purchases.  
- [x] **AC 4:** A card-carousel container displaying featured products, clearance, and most sold items.

#### Tasks
- [x] **AC 1:** Create Product and Batch models.
- [x] **AC 1:** Reasearch for texts of Products Fixtures.
- [x] **AC 1:** Generate images in Adobe Firefly for the products; no free databases contained images of to-be-sold products.
- [x] **AC 1:** Create fixtures for Products, Dietary Categories and Batches. 
- [x] **AC 1:** Create mini cards of the products with main information.
- [x] **AC 2:** Search bar implemented through all_products function filters the database data and uses Q to find search terms.
- [x] **AC 3:** Implement Netflix scroll x bar to present Best Sellers and Salles mini cards of the products with main information. This section was changed from a carousel to a Netflix scroll bar in order to improve UX.
- [x] **AC 4:** Generate images in Adobe Firefly and assemble the banners.
