### ISSUE TITLE
User Story #10 - Shopping Bag/Product Page/Toasts 

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#10]
### User Story #10  

As a **Customer**, I want to be able to **easily select the quantity of products** so that I can **ensure I am purchasing the right quantity before checkout.**

#### Acceptance Criteria  
- [X] **AC 1:** Each product page includes a quantity selector (e.g., dropdown or input field with "+" and "-" buttons).  
- [X] **AC 2:** The quantity selector defaults to 1 but allows users to increase or decrease the quantity.  
- [X] **AC 3:** If the quantity exceeds the available stock, an error message or alert is displayed.  

#### Tasks
- [X] **AC 1:** A quantity selector was included to the product detail page.
- [X] **AC 2:** The quantity selector defaults to 1 through a js script.
- [X] **AC 3:** Via batch.quantity as a max parameter, the stock is not exceeded during selection. It is necessary to implement that on the bag page.
