### ISSUE TITLE
User Story #11 - Shopping Bag

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#11]
### User Story #11  

As a **Customer**, I want to be able to **manage my shopping bag** so that I can **check if the products selected are being added and monitor my spending.**

#### Acceptance Criteria  
- [x] **AC 1:** The shopping bag is accessible via a cart icon in the navigation bar.  
- [x] **AC 2:** The shopping bag displays the list of added products (names and selected quantities).  
- [x] **AC 3:** The subtotal, taxes, and grand total are calculated and displayed.

#### Tasks
- [x] **AC 1/AC 2/AC 3:** The bag page handles all products selected and added to the cart and also provides the prices, delivery costs and grand-total. This feat integrates the main product's manipulation functions through cache data.
