### ISSUE TITLE
User Story #12 - Shopping Bag Notification (Toasts)

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#12]
### User Story #12  

As a **Customer**, I want to be able to **view notifications indicating addition, reduction and removal of items in my shopping bag** so that I can **know immediately if my actions are reflected on my shopping bag**

#### Acceptance Criteria  
- [X] **AC 1:** A toast notification appears after any action (e.g., item added, quantity updated, item removed).
- [X] **AC 2:** Notifications are visible for a few seconds before fading automatically.  

#### Tasks
- [X] **AC 1:** Toasts notification system implemented.
- [X] **AC 2:** Toasts fade automatically within 30 seconds, so, the user have the time to read the messages.
