### ISSUE TITLE
User Story #14  - Checkout Page

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#14]
### User Story #14

As a **Customer**, I want to be able to**visualise an order confirmation after checkout** so that I can **verify the order details and be certain that all steps of purchase were concluded with success**

#### Acceptance Criteria  
- [x] **AC 1:** The checkout page includes fields for shipping and billing details.  
- [x] **AC 2:** Fields include validation for required inputs (e.g., address, city, zip code).  
- [x] **AC 3:** Payment is processed securely via Stripe integration.  

#### Tasks

- [x] **AC 1:** Created the Checkout app and form.  
- [x] **AC 1:** Adjusted Stripe settings and Webhook configurations to handle batches as units and accommodate the Ireland Eircode system. (This was a source of many bugs and took more time than initially planned.) 
- [x] **AC 2:** Implemented text helpers for validation. Initially, a regex validation was applied to the Eircode field, but it caused incompatibilities with the `postal_code` field from Stripe. The solution was to remove the regex and define it as a `CharField` (255 characters) to avoid conflicts with Stripe's address dictionary.  
- [x] **AC 3:** Integrated Stripe payment system through Webhooks, the Webhook Handler, and Checkout app views.
