### ISSUE TITLE
User Story #15 - Order Confirmation Email

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#15]
### User Story #15 

As a **Customer**, I want to be able to **receive an email with the confirmation of my order** so that I can **be reassured that my order was confirmed.

#### Acceptance Criteria  
- [x] **AC 1:** Upon successful payment, the system sends a confirmation email with order details.  
- [x] **AC 2:** The email includes the order number, list of items, total amount, and delivery information.  

#### Tasks
- [X] **AC 1:** Django handles the automatic emails to the backend through Stripe webhook response.
- [X] **AC 1:** The email templates are available and implemented through methods in the checkout app.
- [x] **AC 1:** pesciotti_test@gmail.com is set to deliver emails to user emails.
- [X] **AC 2:** By incorporating Django tags and the Order and OrderLine databases all the listed information is parsed to the customer emails.
