### ISSUE TITLE
User Story #18 - Add a New Product in Admin Panel

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#18]
### User Story #18  

As a **Store Owner**, I want to be able to** Add a new product (finger food or appetizer)** so that I can **use the website to present the customers with a new product**

#### Acceptance Criteria  
- [X] **AC 1:** *Partially** The admin panel has a dedicated section for adding new products.
- [X] **AC 2:** *Partially** The product creation form includes fields from the product model.
- [X] **AC 3:** Validation ensures all required fields are completed before submission.

#### Tasks
- [x] **AC 1/AC 2:** **Partially** Implemented. The admin panel allows for editing the price and best-seller category. Full editing of products was not implemented, as products in the database behave more like categories and are not associated with a unit number in this structure. Furthermore, considering the small business nature, producing 15 types of traditional Brazilian appetizers, it's unlikely that new products would be added regularly. If the manager decides to drop a product, the product page will be set to indicate "out of stock."
- [x] **AC 3:** Validation is handled through custom messages and displayed via toasts.
