### ISSUE TITLE
User Story #19 - Add New Batch of Products

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#19]
### User Story #19 

As a **Store Owner**, I want to be able to **Add a new batch of an existing product** so that I can **keep records of expiry dates and quantities and maintain picture and general information of an existing product**

#### Acceptance Criteria  
- [X] **AC 1:** The admin panel allows batch management for existing products
- [X] **AC 2:** Store owners can add a new batch by selecting an existing product.
- [X] **AC 3:** The batch creation form includes fields for the batch number and expiry date.
- [X] **AC 4:** **Changed** Expired batches are flagged and excluded from active stock.

#### Tasks
- [x] **AC 1:** The shop admin's "Manage Batches" panel provides a quick way to set promotions, check expiry dates, and delete batches. Additionally, the shop manager can thoroughly edit an existing batch via a form based on the `Batch` model. The `sale_price` is calculated automatically by a method in the `Batch` model, through the multiplication of `product.price` and `batch.discount_percentage`.  
- [x] **AC 2/AC 3:** Accessible via `shop_admin/add_a_batch`, this feature allows the shop admin to add a new batch using a form. Fields such as batch number and expiry date are required to submit a new batch.  
- [x] **AC 4:** **Changed:** To ensure the web application remains functional after the project submission deadline without requiring batch maintenance, this feature was dropped. However, in a real-world scenario, it would be considered essential.
