### ISSUE TITLE
User Story #2 - Deals, Clearances (Home Page/Products Page)

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#2]
### User Story #2  

As a **Customer**, I want to be able to **view deals, clearance products, and special offers** so that I can **take advantage of special prices on products.**

#### Acceptance Criteria  
- [x] **AC 1:** The product pages consist of sections pre-filtered by main categories in the navigation bar or a category menu.  
- [x] **AC 2:** Clicking on a category filters the product database list to display only the selected type.  

#### Tasks
- [x] **AC 1/2**: Create fixtures for Products, Dietary Categories and Batches. Due to a lack of photographic samples, the "Assorted Bundles" category was dropped from this task. So, AI-generated images could not create reality-accurate images of various finger foods in the same prompt/image.
https://github.com/hpesciotti/bffs-brazilian-finger-foods/issues/27
https://github.com/hpesciotti/bffs-brazilian-finger-foods/commit/88c954a49864c026417c0360f6459b1e665acdc7
https://github.com/hpesciotti/bffs-brazilian-finger-foods/commit/88c954a49864c026417c0360f6459b1e665acdc7
https://github.com/hpesciotti/bffs-brazilian-finger-foods/commit/d1de10cf6548fe989f7fd57702508e48744100d1
