### ISSUE TITLE
User Story #20 - Sales and Clearance notification on Admin Page

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#20]
### User Story #20  

As a **Store Owner**, I want to be able to **Use the expiry dates or quantities to create special offers** so that I can **maintain stock control and reduce food waste and financial loss. **

#### Acceptance Criteria  
- [ ] **AC 1:** The admin panel includes a feature to create special offers for specific products, considering approaching expiry dates and overstocked products.  
- [ ] **AC 2:** Notifications alerting the store owner to create offers for products nearing expiry.
- [ ] **AC 3:** Discounted products are highlighted on the customer-facing product page with labels (e.g., "Clearance" or "Special Offer").
