### ISSUE TITLE
User Story #23 - Policy/Terms and Conditions

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#23]
#### User Story #23

As a **Store Owner**, I want to be able to **Have a policy page with terms and conditions** so that I can **present to the customer the general legal terms of online shopping.**

##### Acceptance Criteria
- [x] **AC 1:** A policy page is accessible from the website footer with a link labelled "Terms and Conditions."
- [x] **AC 2:** A checkbox confirming customer acceptance of terms is included at checkout.

##### Tasks
- [x] **AC 1:** A policy document generated by freeprivacypolicy is accessible from the website footer. This document covers the fictional company's main activities and website.
- [x] **AC 2:** A generic Terms and Conditions broadly covering the shop's activities was generated through AI, as I don't have any knowledge of commercial law in EU/Ireland.
- [x] **AC 2:** Terms and Conditions are displayed with a check box to the user during checkout.
