### ISSUE TITLE
User Story #25 - Social Media

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#25]
#### User Story #25

As a **Store Owner**, I want to be able to **have a social media presence** so that I can **promote BFFs products on social media**.

##### Acceptance Criteria
- [x] **AC 1:** Make the brand know through Facebook Business and other relevant Social Media.
- [x] **AC 2:** Create an newsletter.

##### Tasks
- [x] Create a Facebook business page and an Instagram Page.
- [x] Implement a newsletter signup form.
