### ISSUE TITLE
User Story #3 - Product Cards (Home and Products)

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#3]
### User Story #3  

As a **Customer**, I want to be able to **browse the products advertised** so that I can **get general information, such as product image, price, allergens, and ingredients.**

#### Acceptance Criteria  
- [x] **AC 1:** Product pages, listed by categories, feature products displayed in a grid or list format with images, names, and prices.  
- [x] **AC 2:** Clicking on a product redirects the user to a detailed product page.  

#### Tasks

- [x] **AC 1:** Create mini cards of the products with the main information to be displayed on the home page.
- [x] **AC 1:** Search bar implemented through all_products function filters the database data and uses Q to find search terms.
- [x] **AC 1:** Implement Netflix scroll x bar to present Best Sellers and Salles mini cards of the products with main information. This section was changed from a carousel to a Netflix scroll bar in order to improve UX.
- [x] **AC 1:** Product pages, filtered by various categories, in large devices have a variable scroll with all products in rows displaying a bigger 16/9 aspect ratio picture with detailed information. On mobile devices, products are listed with cards with reduced details to cater to this small screen, and they are also listed on one scrollable page.
- [x] **AC 2:** Clicking on a product redirects the user to a product detail page. This page contains the quantity of the packages, allergens, cooking process, storage condition, ingredients, historical description and nutritional chart in accordance with EU standards, with 100g, portions and daily intake of nutrients.
