### ISSUE TITLE
User Story #4 - Products - Categories Pages and Filtering

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#4]
### User Story #4  

As a **Customer**, I want to be able to **effortlessly find products that cater to a dietary preference or condition** so that I can **sort the available products to filter the desired appetizer (gluten-free, dairy-free, vegan) or regarding the cooking process (fried/baked) or assorted bundles.**

#### Acceptance Criteria  
- [x] **AC 1:** A filter menu is available on the product listing page with options for:  
  - Gluten-free  
  - Dairy-free  
  - Vegan  
  - Fried  
  - Baked  
  - Assorted Bundles  
- [x] **AC 2:** A sorting feature includes options for prices.  
- [x] **AC 3:** Selected filters dynamically update the displayed products.  

#### Tasks

- [x] **AC 1:** Create fixtures for Products, Dietary Categories and Batches. Due to a lack of photographic samples, the "Assorted Bundles" category was dropped from this task. So, AI-generated images could not create reality-accurate images of various finger foods in the same prompt/image. 
- [x] #27
 - 88c954a49864c026417c0360f6459b1e665acdc7
 - 88c954a49864c026417c0360f6459b1e665acdc7
 - d1de10cf6548fe989f7fd57702508e48744100d1
