### ISSUE TITLE
User Story #5 - Product Page

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#5]
### User Story #5  

As a **Customer**, I want to be able to **view a product page with general information of a selected appetizer** so that I can **see ingredients, dietary information, history, and the region of Brazil.**

#### Acceptance Criteria  
- [x] **AC 1:** The product page includes:  
  - Full-size product image  
  - Ingredients list  
  - Dietary information table  
  - Product description, including history and origin in Brazil  
- [x] **AC 2:** The information should be presented in a responsive layout like an accordion.  

#### Tasks

 - [x] **AC 1**: Product detail page contains the quantity of the packages, allergens, cooking process, storage condition, ingredients, historical description and nutritional chart in accordance with EU standards, with 100g, portions and daily intake of nutrients.
 - [x] **AC 2**: The product's price, allergens, qty and dietary information are clearly displayed alongside the image. Information such as, ingredients, historical description and nutritional are kept inside an accordion.
