### ISSUE TITLE
User Story #6 - FAQ Page

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#6]
### User Story #6  

As a **Customer**, I want to be able to **know about storage, cooking information, and general frequently asked questions** so that I can **read about any possible doubts regarding the offered products.**

#### Acceptance Criteria  
- [X] **AC 1:** The About page includes the following:  
  - Storage instructions  
  - Cooking or preparation guidelines  
  - A FAQ section  
- [x] **AC 2:** The FAQ section answers common questions like shelf life, freezing compatibility, and preparation methods.  
- [x] **AC 3:** The information is easy to navigate and clear for comprehension.  

#### Tasks
- [x] **AC 1:** Since most of the "About" related information is already available to users on the product detail pages, it was decided during development to create only an FAQs page instead.  
- [x] **AC 2:** Through benchmarking common customer questions about similar products, a selection of questions was saved in an FAQ database. The FAQ page, using an accordion layout, dynamically renders all the stored questions via a `for` loop.  
- [x] **AC 3:** The accordion layout provides an easy-to-navigate page, accessible via the footer.
