### ISSUE TITLE
User Story #7  - Register an User/Customer Account

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#7]
### User Story #7  

As a **Customer**, I want to be able to **easily create/register a user account** so that I can **manage key user information, such as address and personal details.**

#### Acceptance Criteria  
- [x] **AC 1:** The registration page is accessible from the home page via a "Sign Up" button.  
- [x] **AC 2:** Error messages are displayed for invalid inputs.  
- [x] **AC 3:** Registration is handled by Django Allauth. 

#### Tasks
- [x] **AC 1:** Added a customized Sign-Up page using Django AllAuth.  
- [x] **AC 2:** Messages are displayed through default error handling and toast notifications.  
- [x] **AC 3:** User registration is seamlessly handled by Django AllAuth.
