### ISSUE TITLE
User Story #8 - Customer Profile Page

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#8]
### User Story #8  

As a **Customer**, I want to be able to **manage my account through a user profile** so that I can **manage my order history and personal information.**

#### Acceptance Criteria  
- [x] **AC 1:** Users can access their profile via a "My Account" link in the navigation bar.  
- [x] **AC 2:** The user profile page includes sections for:  
  - Personal details (e.g., name, email)  
  - Address details  
  - Order history (sortable by date and status)  
- [x] **AC 3:** Users can update their information and save changes.  

#### Tasks
- [x] **AC 1:** "My Account" is present in the navigation bar, and through Django AllAuth, user data validation and storage are handled seamlessly.  
- [x] **AC 2:** All the mentioned fields are collected either by filling out the profile form or through the checkout form if the "Save my personal details" checkbox is selected.  
- [x] **AC 3:** Similarly to AC 2, users can edit their information on the profile page or overwrite their personal details during checkout if the checkbox is checked.
