### ISSUE TITLE
User Story #9 - Customer Login

### ISSUE THREAD

**Issue by hpesciotti** [hpesciotti/bffs-brazilian-finger-foods#9]
### User Story #9  

As a **Customer**, I want to be able to **effortlessly log in/ logout of my account** so that I can **efficiently access my account**

#### Acceptance Criteria  
- [x] **AC 1:** The login page is accessible from the home page via a "Log In" button.  
- [x] **AC 2:** Users can log in using their registered email and password.  
- [x] **AC 3:** A "Log Out" button is always visible when the user is logged in.  
- [x] **AC 4:** Error messages are displayed for invalid login attempts (e.g., incorrect email or password).  

#### Tasks
- [x] **AC 1:** The login page is accessible for unlogged users on both versions of the navigation bar.  
- [x] **AC 2:** The Django AllAuth library allows users to log in by entering their registered email and password.  
- [x] **AC 3:** The Log Out nav-item is accessible through the profile icon if the user is logged in.  
- [x] **AC 4:** The Django AllAuth library handles all user-related messaging regarding user states and data.
